[package]
name = "clevercloud-sdk"
description = "A rust client and structures to interact with the Clever-Cloud API."
version = "0.5.2"
edition = "2021"
rust-version = "1.56"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/CleverCloud/clevercloud-sdk-rust"
keywords = [
    "clevercloud",
    "sdk",
    "logging",
    "metrics",
    "jsonschemas",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.52"
oauth10a = "^1.2.4"
log = { version = "^0.4.14", optional = true }
hyper = { version = "^0.14.16", default-features = false }
schemars = { version = "^0.8.8", features = [
    "chrono",
    "indexmap",
    "uuid",
    "bytes",
    "url",
], optional = true }
serde = { version = "^1.0.133", features = ["derive"] }
serde_repr = "^0.1.7"
tracing = { version = "^0.1.29", optional = true }
tracing-futures = { version = "^0.2.5", optional = true }

[features]
default = ["logging"]
jsonschemas = ["schemars"]
logging = ["oauth10a/logging", "tracing/log-always", "log"]
metrics = ["oauth10a/metrics"]
trace = ["oauth10a/trace", "tracing", "tracing-futures"]
tokio = ["oauth10a/tokio", "tracing-futures/tokio"]
