[package]
name = "clevercloud-sdk"
description = "A Rust client and structures to interact with the Clever-Cloud API."
version = "0.15.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/CleverCloud/clevercloud-sdk-rust"
keywords = ["clevercloud", "sdk", "logging", "metrics", "jsonschemas"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["logging", "network-group"]
jsonschemas = ["dep:schemars"]
logging = ["dep:log", "oauth10a/logging", "tracing/log-always"]
metrics = ["oauth10a/metrics"]
tracing = ["oauth10a/tracing", "dep:tracing"]
network-group = ["dep:base64", "x25519-dalek", "dep:rand_core", "dep:cidr"]

[dependencies]
base64 = { version = "^0.22.1", optional = true }
chrono = { version = "^0.4.41", features = ["serde"] }
cidr = { version = "^0.3.1", features = ["serde"], optional = true }
oauth10a = { path = "../oauth10a-rust", default-features = false, features = [
    "client",
    "serde",
    "rest",
    "sse",
    "zeroize",
] }
log = { version = "^0.4.27", optional = true }
rand_core = { version = "^0.9.3", features = ["os_rng"], optional = true }
schemars = { version = "^0.8.22", features = [
    "chrono",
    "indexmap1",
    "uuid1",
    "bytes",
    "url",
], optional = true }
serde = { version = "^1.0.219", features = ["derive"] }
serde_repr = "^0.1.20"
serde_json = "^1.0.140"
thiserror = "^2.0.12"
tracing = { version = "^0.1.41", optional = true }
uuid = { version = "^1.17.0", features = ["serde", "v4"] }
x25519-dalek = { version = "^2.0.1", features = [
    "zeroize",
    "static_secrets",
], optional = true }
zeroize = { version = "^1.8.1", features = ["serde", "derive"] }
env-capture = { git = "https://gitlab.corp.clever-cloud.com/CedricLG/env-capture", features = [
    "serde",
] }

[dev-dependencies]
tracing-subscriber = { version = "^0.3.19", features = ["env-filter"] }
