[package]
name = "clevercloud-sdk"
description = "A rust client and structures to interact with the Clever-Cloud API."
version = "0.10.13"
edition = "2021"
rust-version = "1.60.0"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/CleverCloud/clevercloud-sdk-rust"
keywords = [
    "clevercloud",
    "sdk",
    "logging",
    "metrics",
    "jsonschemas",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.66"
oauth10a = "^1.3.18"
log = { version = "^0.4.17", optional = true }
hyper = { version = "^0.14.25", default-features = false }
schemars = { version = "^0.8.12", features = [
    "chrono",
    "indexmap1",
    "uuid1",
    "bytes",
    "url",
], optional = true }
serde = { version = "^1.0.155", features = ["derive"] }
serde_repr = "^0.1.11"
thiserror = "^1.0.39"
tracing = { version = "^0.1.37", optional = true }
tracing-futures = { version = "^0.2.5", optional = true }
uuid = { version = "^1.3.0", features = ["serde", "v4"] }

[features]
default = ["logging"]
jsonschemas = ["schemars"]
logging = ["oauth10a/logging", "tracing/log-always", "log"]
metrics = ["oauth10a/metrics"]
trace = ["oauth10a/trace", "tracing", "tracing-futures"]
tokio = ["oauth10a/tokio", "tracing-futures/tokio"]
