[package]
name = "cleverctl"
description = "A command line interface that use the clevercloud-sdk"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
version = "0.10.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.57"
clevercloud-sdk = { path = "../..", features = ["tokio", "metrics", "trace", "jsonschemas"] }
clap = { version = "^3.2.20", features = ["derive"] }
config = "^0.13.2"
paw = "^1.0.0"
serde = { version = "^1.0.144", features = ["derive"] }
serde_json = "^1.0.85"
serde_yaml = "^0.9.11"
thiserror = "^1.0.34"
tokio = { version = "^1.21.0", features = ["full"] }
tracing = "^0.1.36"
tracing-subscriber = { version = "^0.3.15", default-features = false, features = ["std", "ansi", "tracing-log"] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
