[package]
name = "cleverctl"
description = "A command line interface that use the clevercloud-sdk"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
rust-version = "1.64.0"
version = "0.10.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.66"
clevercloud-sdk = { path = "../..", features = ["tokio", "metrics", "trace", "jsonschemas"] }
clap = { version = "^4.1.8", features = ["derive"] }
config = "^0.13.3"
paw = "^1.0.0"
serde = { version = "^1.0.155", features = ["derive"] }
serde_json = "^1.0.94"
serde_yaml = "^0.9.19"
thiserror = "^1.0.39"
tokio = { version = "^1.26.0", features = ["full"] }
tracing = "^0.1.37"
tracing-subscriber = { version = "^0.3.16", default-features = false, features = ["std", "ansi", "tracing-log"] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
