[package]
name = "cleverctl"
description = "A command line interface that use the clevercloud-sdk"
version = "0.10.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.53"
clevercloud-sdk = { path = "../..", features = ["tokio", "metrics", "trace", "jsonschemas"] }
clap = { version = "^3.1.18", features = ["derive"] }
config = "^0.13.1"
paw = "^1.0.0"
serde = { version = "^1.0.137", features = ["derive"] }
serde_json = "^1.0.81"
serde_yaml = "^0.8.24"
thiserror = "^1.0.31"
tracing = "^0.1.34"
tracing-subscriber = { version = "^0.3.11", default-features = false, features = ["std", "ansi", "tracing-log"] }
tokio = { version = "^1.18.2", features = ["full"] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
