use core::{net::IpAddr, str};

use base64::Engine;
use oauth10a::client::{
    ClientError, RestClient,
    sse::{Json, SseClient, SseStreamBuilder},
};
use serde::{Deserialize, Serialize};
use tracing::debug;

use crate::Client;

use super::{OwnerId, network_group_id::NetworkGroupId, peer::PeerId};

// ERROR ///////////////////////////////////////////////////////////////////////

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("failed to get WireGuard configuration for owner '{0}', network group '{1}', {0}")]
    Get(String, NetworkGroupId, ClientError),
    #[error("network group identifier, expected {expected}, found {found}")]
    NetworkGroupIdMismatch {
        expected: NetworkGroupId,
        found: NetworkGroupId,
    },
}

// PEER VIEW ///////////////////////////////////////////////////////////////////

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeerView {
    /// the uuid of the instance
    #[serde(rename = "peer_id")]
    pub peer_id: PeerId,
    /// typically "10.101.2.4"
    #[serde(rename = "peer_ip")]
    pub peer_ip: IpAddr,
    /// typically "app_something.m.ng_abcdefg.ng.clever-cloud.com"
    #[serde(rename = "peer_hostname")]
    pub peer_hostname: String,
}

// RAW WIREGUARD CONFIG ////////////////////////////////////////////////////////

/// WireGuard configuration decoded from Base64.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawWireGuardConfig(pub String);

impl RawWireGuardConfig {
    pub const PREFIX: &'static str = "\n####networkgroups start\n";
    pub const SUFFIX: &'static str = "\n####networkgroups end\n";
    pub const WG_PRIVATE_KEY_PLACEHOLDER: &'static str = "<%PrivateKey%>";
}

impl AsRef<str> for RawWireGuardConfig {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl Serialize for RawWireGuardConfig {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        base64::engine::general_purpose::STANDARD
            .encode(&self.0)
            .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for RawWireGuardConfig {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let base64_encoded = String::deserialize(deserializer)?;
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(&base64_encoded)
            .map_err(serde::de::Error::custom)?;
        let decoded_utf8 = str::from_utf8(&decoded).map_err(serde::de::Error::custom)?;
        Ok(Self(decoded_utf8.trim().to_owned()))
    }
}

// WIREGUARD CONFIGURATION /////////////////////////////////////////////////////

/// Event generated by OVD on configuration updates.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WireGuardConfiguration {
    #[serde(rename = "ngId")]
    pub ng_id: NetworkGroupId,
    #[serde(rename = "peerId")]
    pub peer_id: PeerId,
    #[serde(rename = "peers")]
    pub peers: Vec<PeerView>,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "configuration")]
    pub configuration: RawWireGuardConfig,
}

impl WireGuardConfiguration {
    pub async fn get(
        client: &Client,
        owner_id: &OwnerId,
        ng_id: &NetworkGroupId,
    ) -> Result<Self, Error> {
        let endpoint = format!(
            "{}/v4/networkgroups/organisations/{owner_id}/networkgroups/{ng_id}/external-peers",
            client.endpoint,
        );

        #[cfg(feature = "tracing")]
        debug!("execute a request to get WireGuard configuration, endpoint: '{endpoint}'");

        let wg_configuration: WireGuardConfiguration = client
            .get(&endpoint)
            .await
            .map_err(|e| Error::Get(owner_id.to_owned(), *ng_id, e))?;

        if wg_configuration.ng_id != *ng_id {
            return Err(Error::NetworkGroupIdMismatch {
                expected: *ng_id,
                found: wg_configuration.ng_id,
            });
        }

        Ok(wg_configuration)
    }

    pub fn sse(
        client: &Client,
        owner_id: &OwnerId,
        ng_id: &NetworkGroupId,
        peer_id: &PeerId,
    ) -> SseStreamBuilder<Client, String, Json<Self>> {
        let endpoint = format!(
            "{}/v4/networkgroups/organisations/{owner_id}/networkgroups/{ng_id}/peers/{peer_id}/wireguard/configuration/stream",
            client.endpoint
        );

        #[cfg(feature = "tracing")]
        debug!(
            "create SSE stream builder to subscribe to WireGuard configuration's, endpoint: '{endpoint}'"
        );

        client.sse(&endpoint)
    }
}
