---
name: Continuous integration
on: [ push, pull_request ]
jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rust:
          - 1.74.1
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --features metrics --features jsonschemas --features trace --features tokio
  test:
    name: Test library
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rust:
          - 1.74.1
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
      - uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --verbose
  format:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --all -- --check
  clippy:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --features metrics --features jsonschemas --features trace --features tokio -- -D warnings
  doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --features metrics --features jsonschemas --features trace --features tokio
...
